# Generated by Django 4.0.2 on 2022-02-22 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_activity_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-updated', '-created'], 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
